version: '3.8'

services:
  api:
    image: pablowinck/palestra-sincronizacao:1.0
    environment:
      DATABASE_URL: vertx-reactive:mysql://mysql:3306/compras
      DATABASE_PASSWORD: 123456
      MONGODB_CONNECTION_STRING: mongodb://mongodb:27017
      API_URL: http://api2:8081
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
#    expose:
#      - "8080"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 300M
  api2:
    image: pablowinck/palestra-sincronizacao:1.0
    environment:
      DATABASE_URL: vertx-reactive:mysql://mysql:3306/compras
      DATABASE_PASSWORD: 123456
      MONGODB_CONNECTION_STRING: mongodb://mongodb:27017
      SERVER_PORT: 8081
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    #    expose:
    #      - "8080"
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 300M
  mysql:
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: compras
    ports:
      - "3306:3306"

  mongodb:
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      timeout: 20s
      retries: 10
    ports:
      - "27017:27017"

